name: Vuepress build & Publish

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm install
        npm run docs:build
      env:
        CI: true
    - name: Archive Production Artifact
      uses: actions/upload-artifact@master
      with:
        name: web-build
        path: docs
  publish:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      -
        name: Checkout
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: web-build
      -
        name: Deploy
        if: success()
        uses: crazy-max/ghaction-github-pages@master
        with:
          target_branch: gh-pages
          build_dir: web-build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
